version: "3.8"

services:
  app:
    image: ghcr.io/asynchronously-w/docker-stack-demo:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"